.eslintrc.json, package.json
1)
I understand you use `yarn` v1.
you not define it in `package.json`.
so if I run `yarn install` yarn automatically upgrade to v3.
so I define  the yarn version in `package.json`.
2)
in windows when I run the project, I get the error ` delete 'CR' prettier/prettier` in every file.
this happen because the git default settings in `core.autocrlf` is automatically convert them when we check out files.
to fix it I define  the `eslintrc` automatically choose the `endOfLine`.
=> Fix 'yarn' and 'eslintrc' configuration files

.github/workflows/ci.yml, playwright.config.ts
when running on forks, secrets.GITHUB_TOKEN is not available. I don't want the contributors to see a giant red `x` next to their pull request. That's a bad developer experience. let's solve it
irrelevant
=> ci: prevent workflow from failing on forks

src/pages/RealtimeMapPage.tsx, src/pages/components/MapLayers/BusLayer.tsx, src/pages/components/utils/customCluster/customCluster.tsx
`process` doesn't exist in a browser context.
=> fix: remove node.js code from browser context

src/App.tsx
Fixes #83 
I was able to identify three pages which made use of the arguments:
- TimelinePage
- GapsPage
- SingleLineMapPage
I have made the following changes:
=> fix: remove unnecessary search params

README.md, index.html, package.json, playwright.config.ts, tests/dashboard.spec.ts, tests/example.spec.ts, tsconfig.json, vite-env.d.ts, vite.config.ts, yarn.lock
Followed the instructions to migrate from CRA to Vite - https://dev.to/henriquejensen/migrating-from-create-react-app-to-vite-a-quick-and-easy-guide-5e72
Fixes Issue 77 - https://github.com/hasadna/open-bus-map-search/issues/77
=> Migrating from CRA to Vite

.dockerignore, .gitignore, Dockerfile
Vite build goes to a different directory - `/dist` instead of `/build`
@knightcube your approval will be appriciated
=> fix: dockerfile to vite build

.github/workflows/unittest.yml, package.json, setupTests.ts, src/pages/components/utils/index.test.ts, src/pages/useGapsList.ts, tsconfig.json, vite.config.ts, yarn.lock
test that testing sortByMode util
<-- paste here -->
=> test: add first unit test

src/pages/components/utils/index.ts
`toSorted` browser support isn't wide enough
not to mention node.js support
let's use `sort` for now
=> refactor: avoid toSorted

src/api/useVehicleLocations.ts
we have an error - we send "operatorRefField=undefined" in our requests and it makes them fail on the backend side
=> hotfix: operatorRefField

src/pages/dashboard/ArrivalByTimeChart/ArrivalByTimeChart.tsx
The timeline graph at the dashboard (אחוזי יציאה מסך הנסיעות לפי זמן) was changed to be **ltr** even though the application is in Hebrew (basically with **rtl** orientation.
See the screenshot below.
This one closes the issue #139
=> Reverse the timeline graph XAxis to be with  'ltr' orientation

src/App.scss, src/App.tsx, src/locale/he.json, src/pages/components/header/menu/Menu.tsx, src/pages/components/header/menu/menu.scss, src/pages/components/header/sidebar/SideBar.tsx, src/pages/components/header/sidebar/sidebar.scss, src/resources/variables.scss
closes #132
new design for a sidebar
desktop:
mobile (menu closed):
mobile (menu open):
=> feat: improve sidebar & logo design

src/App.tsx, src/pages/components/header/sidebar/SideBar.tsx, src/pages/components/header/sidebar/menu/Menu.tsx, src/pages/components/header/sidebar/menu/menu.scss, src/routes/index.tsx
currently menus (pages) list passed from App to Sidebar and then to Menu component
this can be simplified
by importing the pages constant directly from router file
closes #182 
<paste here>
=> refactor: import pages directly to menu

src/App.scss, src/App.tsx, src/layout/LayoutContext.tsx, src/pages/components/header/Header.tsx, src/pages/components/header/sidebar/SideBar.tsx, src/pages/components/header/sidebar/sidebar.scss
=> feat: change mobile menu to use drawer

src/locale/en.json, src/locale/he.json, src/pages/components/header/sidebar/GitHubLink/GitHubLink.scss, src/pages/components/header/sidebar/GitHubLink/GitHubLink.tsx, src/pages/components/header/sidebar/SideBar.tsx, src/pages/components/header/sidebar/sidebar.scss, src/resources/texts.tsx
Resolving #205 
Mobile:
- Add a logo to the sidebar menu.
Mobile & Desktop:
- Add a GitHub icon that navigates to the repo link.
- Add dividers to the sidebar menu.
Desktop:
Mobile:
=> issue #205: GitHub repo link

src/api/gtfsService.ts
How: filter the routes date when we get them from back-end
Why: it fixes stop duplication and don't use yesterday routes
Solves issue #134 from front. You still should change the back-end or not, up to you.
* I read that you discussed about changing the back-end so it will not send the routes of yesterday but as I see it, we should have a "protection in the front" in case the back-end sends not relevant routes like it happens now :) 
<paste here>
Before:
https://github.com/hasadna/open-bus-map-search/assets/76536506/169d8e59-3e0a-4b48-9c50-83fe4403c7c9
After:
https://github.com/hasadna/open-bus-map-search/assets/76536506/0cb0da60-9b44-4d1b-8d8a-182446021eb8
=> fix: Use Only Relevant Routes

src/App.scss, src/pages/components/Widget.stories.tsx, src/pages/dashboard/DashboardPage.scss, src/shared/shared.css
snice widget util (it also can be called `card`) used in multiple places
i think - it can be better to moved it to `shared` folder
not relevant here
=> refactor: move widget util to shared folder

src/locale/en.json, src/locale/he.json, src/pages/About.tsx
Removed TEXT_KEYS from About page
see this comment: https://github.com/hasadna/open-bus-map-search/issues/161#issuecomment-1826830052
and if you have any other suggestions on the translation, I'll change it.
=> Removing texts#161 - About page

src/pages/dashboard/ArrivalByTimeChart/ArrivalByTimeChart.tsx
Update for #254 #215 
The collapsible menu on the dashboard page was slow when opening and closing
=> fix: collapsible menu slowness

src/App.tsx, src/layout/index.tsx
in order to make App component shorter (now it is 140 lines)
i think it can be better to move all the layout stuff to separate `layout` component
This will make App component code shorter and cleaner
not relevant here
=> refactor: move layout logic to separate component

src/pages/RealtimeMapPage.tsx
=> fix(mobile): hide input labels at realtimeMap page

src/locale/en.json, src/locale/he.json, src/pages/TimelinePage.tsx, src/pages/components/DateSelector.tsx, src/pages/components/DisplayGapsPercentage.tsx, src/pages/components/FilterPositionsByStartTimeSelector.tsx, src/pages/gaps/index.tsx
Removed from: FilterPositionsByStartTimeSelector, GapsPage, DisplayGapsPercentage, DateSelector, and TimelinePage.
=> Removing texts part c#161

src/routes/index.tsx, src/shared/Preloader.tsx
it can be better to us same preloader also at lazy loaded pages
=> chore: change page preloader to circular

src/pages/dashboard/DashboardPage.tsx
explanation for users added at the top of dashboard page
related to #109
=> feat: add explanation at the top of dashboard page

src/locale/en.json, src/locale/he.json, src/pages/Profile.tsx, src/pages/components/LineSelector.tsx, src/pages/components/MapLayers/BusToolTip.tsx, src/pages/components/MinuteSelector.tsx, src/pages/components/OperatorSelector.tsx, src/pages/components/RouteSelector.tsx, src/pages/components/StopSelector.tsx, src/pages/components/TimeSelector.tsx
Removed from: TimeSelector, StopSelector, RouteSelector, OperatorSelector, MinuteSelector, LineSelector and Profile.
Next, maybe in this PR, I want to remove texts from BusToolTip. but I'm not sure where to find it in the UI, and I need to check because some translations are missing there even in the texts file...
=> Removing texts part d#161

src/api/useVehicleLocations.ts
slove #292 
just easy way by add to observable key
`operatorRef lineRef`
for getting new time from server
=> fix: useVehicleLocation cache mechanism

.github/workflows/preview.yml, vite.config.ts
not perfect (the routing is misconfigured), but good enough for now.
=> ci: add preview link

.github/workflows/preview.yml
when `secrets.AWS_SECRET_ACCESS_KEY` isn't accessible (on forks), the preview job shouldn't be running.
irrelevant
=> ci: disable preview attempts on fork

README.md, src/layout/index.tsx, src/pages/DataResearch.tsx, src/pages/DataResearch/DataResearch.scss, src/pages/DataResearch/DataResearch.tsx, src/routes/index.tsx, src/shared/Widget.tsx
add a research secret route with stacked chart 
solve #261 and #262
=> feat: create research route

CONTRIBUTION.md, README.md
=> docs: create contribution.md file

src/pages/Map.scss
Hey there, sorry for the delay with delivering this feature, I had tons of work lately.
I thought it would be nice to implement it for the /map page, as it has pretty much the same layout and style for both mobile & desktop. Let me know if you approve it, then I'll incorporate this feature as well.
Not expanded:
Expanded:
=> feat: Disable mobile-only media query

src/pages/historicTimeline/index.tsx, src/routes/index.tsx
extra input labels  removed at mobile view
also added a title and page description
=> fix(historicPage): remove redundant labels at mobile view

tests/clearButton.spec.ts, tests/realtimemap.spec.ts
solve the following problem:
by waiting for the other date element to disappear.
(the first element is a leftover from the dashboard page)
=> test: stabilize tests

src/layout/sidebar/GitHubLink/GitHubLink.tsx
Following #221, this adds useCallback for the GitHub link onClick.
=> perf(rendering): useCallback for GitHub link onClick

src/pages/realtimeMap/index.tsx
As I did on Issue #252, I implemented an expand button for the /map page as well.
Works for both mobile & desktop (looks fine on all screens as far as I checked).
!isExpanded:
Expanded:
=> feat: add map expansion button to realtime map page

src/shared/shared.css
resolving issue #375 
dashbord widget  changes in shared.css for performing gap between widgets and removing inner border.
=> fix: gap between widgets #375

src/App.scss, src/routes/index.tsx
We'll make an event,
This code will be reverted afterward.
It's just a temporary ugly thing to put a landing page in here.
=> chore: add temporary route for the version release event

README.md
The link that is supposed to take you to the CONTRIBUTING.md takes you to a non existent CONTRIBUTION.md. I also fixed the hash anchor to take you to the intended part of the page.
=> docs: fixed a dead link in README.md

src/pages/components/Label.tsx
make input visible at dark mode
=> fix: make input labels visible at dark mode

src/layout/ThemeContext.tsx, src/layout/header/ToggleThemeButton.tsx, src/locale/en.json, src/locale/he.json
I updated the **_ThemeContext.tsx_** so the scrollbar on dark mode will be part of the color scheme.
I found the solution in MUI documentation [in this link](https://mui.com/material-ui/react-css-baseline/#scoping-on-children
)
=> fix: scrollbar color on dark mode

src/App.scss, src/routes/index.tsx
remove the temporary route that shown the release event promotion
=> chore: Revert "chore: add temporary route for the version release event (#382)"

src/api/groupByService.ts
fixed #339 problem on frontend side where there were "unknown" bus provider
need to check the agency list and add a new agency to be like the DB
=> fix: Remove unknown data

package-lock.json, package.json, src/pages/dashboard/ArrivalByTimeChart/ArrivalByTimeChart.tsx
Fixes ArrivalByTimeChart being too small on lower resolutions by adding a minimum width to the component
Before:
After:
=> style: Ensure minimum width for ArrivalByTimeChart 

src/pages/components/DateSelector.tsx, src/pages/components/utils/dateAndTime.tsx, src/pages/dashboard/DashboardPage.tsx, src/pages/gapsPatterns/GapsPatternsPage.tsx
Added minimum date = start date to dashboard date picker, and gaps patterns page. 
I changed the DatePicker component to accept minDate. 
The dates before the start date are enabled for the end-date-picker.
=> fix: Block end date#309

src/pages/components/LineSelector.tsx
You now can insert a letter to the line selector that used to get only numbers.
I checked with the api and it gets string for route_short_name(LineNumber).
Also checked locally and i.e: I tried 17א as line and it returned the  correct lines.
This pull request comes to solve issue #520 .
before the change(cannot insert letters):
after the change:
=> fix: line selector can now get letters as well

.github/workflows/preview.yml
I believe that if we'll use pull_request_target, the secrets will be available and previews will be available in forks
=> ci: make previews available on forks

src/pages/ProfileLineDetails.tsx
This is continue of #543 
I changed the section where we display data on the line to look something like the table bellow regarding colors just to be consist.
=> style(line-profile): Change line profile into table look

src/api/gapsService.ts
fix the warning when jest say:
```console.warn
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged. Please refer to http://momentjs.com/guides/#/warnings/js-date/ 
for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: true, _useUTC: true, _l: undefined, _i: null, _f: undefined, _strict: undefined, _locale: [object Object]
Error
at Function.createFromInputFallback (C:\Users\avivh\Desktop\projects\Open_Bus\open-bus-map-search\node_modules\moment\moment.js:324:25)
at configFromString (C:\Users\avivh\Desktop\projects\Open_Bus\open-bus-map-search\node_modules\moment\moment.js:2613:19)
at configFromInput …
```
=> fix: jest warning value provided is not in a recognized RFC2822 or ISO format.

src/pages/components/map-related/MapLayers/BusToolTip.tsx
When pressing on line number to see line profile, it shows the right line information
It used to take line number as id, and now takes the real id for the correct line
This pull request comes to solve issue #565 
before the change(wrong line information):
It gave the wrong information after pressing 25(for the line profile):
And after the change:
=> fix: wrong line profile information

package-lock.json, package.json
vite development server could be upgraded to 5.1.6 latest version (also it better to moved to `devDependecies`)
<paste here>
=> chore: update vite to latest version 5.1.6

.github/dependabot.yml
If all the update grouped to one PR we don't know witch update breaking changes.
if we not set up the `open-pull-requests-limit` the [default it only five PRs](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#open-pull-requests-limit),
=> chore: dependabot disable groups.

tests/timeline.spec.ts
1. Re-enable test ```'Test Verify no duplications in stations list'```
2. Re-enable test ```'Test choosing [Operator -> Line # -> Route -> Stop station] opens the timestamp graph'```
After running the tests locally they seem to pass, most likely a byproduct from the fixes from PR #467 
Closes #460
=> test: Fix a Playwright test

src/pages/dashboard/DashboardPage.scss
* This is probably the minor pull request ever, but the `title` class on dark mode is almost invisibly, so i removed the color for the text and now the title is black (on light mode) and white (on dark mode).
* Tested on all pages related and consumed `title` and all good.
**Before**:
**After**:
=> style: Change `title` color so it will be visible in dark mode

src/layout/header/Header.css, src/layout/header/Header.tsx, src/layout/header/HeaderLinks/HeaderLinks.scss, src/layout/header/HeaderLinks/HeaderLinks.tsx, src/layout/header/LanguageToggle.tsx, src/layout/header/ToggleThemeButton.tsx
Fixes improperly aligned header links by nesting them inside of ```<HeaderLinks />```
=> fix: improperly aligned header links

src/api/gtfsService.ts
Resolves #538 
The filter in the gtfsService was wrong and probably assumed the **to** and **from** dates were the same (see #538)
The correct filter is now in place checking each route against the to and the from dates like it should.
=> fix(gtfs-service-api): change routes filter to correctly check if a route is in the given range

src/layout/sidebar/logo.tsx, src/layout/sidebar/sidebar.scss
These changes have solved the alignment problem in the SVG logo.
In addition, the alignment problem in the "דאטאבוס" text was fixed.
=> fix: databus logo out of alignment in English mode

src/locale/he.json, src/pages/Map.scss, src/pages/components/map-related/MapWithLocationsAndPath.tsx, tests/dashboard.spec.ts
Resolves #579 
The map legend was kind of transparent in dark mode - I fixed it
Note: I have noticed there is a complete mess using different component libraries and configuring each one's dark mode options - the code is cumbersome - maybe we should consider sticking (strictly) with one library (and and replacing the others (e.g. MUI and not AntDesign - I have no personal preference)
Before:
After:
=> fix: dark mode hides map legend

tests/visual.spec.ts
When visually testing the dashboard charts, we want the visual comparison to compare the general patterns of charts rather then expecting the exact same structure
https://help.applitools.com/hc/en-us/articles/4408368066957-useDom-and-enablePatterns-Flags
<paste here>
=> test: enable pattern

src/pages/Map.scss, src/pages/components/map-related/MapIndex.tsx
The icon in the map legend wasn't on the line like in the map
now:
=> fix: in the single line tab the legend icon was not center

src/pages/components/map-related/MapContent.tsx, src/pages/components/map-related/MapFooterButtons/MapFooterButtons.scss, src/pages/components/map-related/MapFooterButtons/MapFooterButtons.tsx, src/pages/components/map-related/MapLayers/BusToolTip.tsx, src/pages/components/map-related/MapWithLocationsAndPath.tsx, src/pages/components/map-related/map-types.ts, src/pages/singleLineMap/index.tsx
https://github.com/hasadna/open-bus-map-search/issues/776
it's not solution with more zoom (i check with the docs and it look like it's the maximum)
=> feat: add to single line map arrowa to navigate between points

src/pages/dashboard/DashboardPage.tsx, src/pages/gapsPatterns/GapsPatternsPage.tsx
@NoamGaash 
Fix description: 
Remove css override for white background that makes text unreadable while on Darkmode
How to test:
1. Go Dashboard/Gap patterns page 
2. select start date that is earlier than end date.
3. A new Alert message should appear above the dates picker with validation error.
4. Change to Dark mode and check that background of the validation error alert is not white and that the message is clear.
=> fix: remove css override of white background on darkmode

src/layout/sidebar/menu/Menu.tsx, src/pages/DonateModal/DonateModal.tsx, src/routes/index.tsx, tests/timeline.spec.ts
Solution for #422 
- Added a Donation Modal that opens when the donation menu item is clicked.
- Created a `DonateModal` component based on the existing `DonationButton`.
- Updated `MainMenu` to include a conditional check for the donation menu item.
- Used `e.preventDefault()` to prevent URL change when clicking the donation menu item.
- Integrated the `DonateModal` into the `MainMenu` component.
- Ensured that donation links in the modal open in a new tab.
=> feat: add Donation Modal as menu item 

src/locale/en.json
Adds missing public appeal translation for the english version of the site
Before: 
After:
=> fix: add missing public appeal translation in english mode

src/api/gtfsService.ts
Fixes issue #856 by adding the required "arrival_time_from" and "arrival_time_to" fields to the gtfs_ride_stops api call. 
Changed the previous api call which utilized the gtfsAPI to an axios call directly to the server with the required data since the gtfsAPI whitelisted the required fields mentioned above which caused the api call to fail.
Still requires futher optimizations since the request is very slow and tests need to be written in future issues.
@NoamGaash
=> fix: rides history page

package-lock.json, package.json, tests/clearButton.spec.ts, tests/visual.spec.ts
Sometimes when tests are visiting the realtime page, they load too-recent data that haven't loaded yet.
This PR suggest to set a specific arbitrary time to ensure the tests will remain consistent
=> test: set fixed time to the map page tests

eslint.config.js, public/service-worker.js, src/App.tsx
Add a service worker to cache GET requests for specific backend and external resources (e.g., open-bus-stride-api, fonts.googleapis.com), excluding HTML, CSS, and JS files. This reduces server load by serving cached responses for those URLs, while ensuring that the latest versions of static assets are always fetched from the network.
=> perf: cache all api responses using a webworker

src/pages/timeBasedMap/index.tsx
fetching the same date and time by default will allow us to implement better caching mechanism for that time
no reason. it's arbitrary
=> perf(map): set default time to pi day

src/layout/sidebar/SideBar.tsx
Fixed the sidebar collapse arrow to change direction based on the language, ensuring proper behavior for both LTR and RTL layouts. This update addresses issues with the arrow direction in Hebrew and other right-to-left languages, improving the user experience in these locales.
=> fix: Fixed sidebar collapse arrow direction for RTL languages

tests/tripExistence.spec.ts
My first test, created by codegen,
Choosing params under "קיום נסיעות" and organize by date/hour.
=> test: add test for trip existence

tests/publicAppeal.spec.ts
Public Appeal menue item should lead to "קול קורא" and its link inside should lead to the Docs page in Hasadna site.
=> test: add tests for public appeal

tests/githubLink.spec.ts
Make sure the corner GitHub icon leads to DataBus GitHub project
=> test: add test for GitHub icon

tests/about.spec.ts
clicking the links under "privacy" should lead to Google analytics
=> test: add tests for 'about' page

src/pages/DonateModal/DonateModal.tsx
**Only a suggestion** for a Temporary fix of the unreadable text in the Donate Modal while in Dark mode.
Until I (or someone else) will be able to change the text color for *white* in dark mode and *black* in light mode,
I changed it to blue (as the button) so it will be readable in dark AND light modes.
=> fix: Temporary fix suggestion of the unreadable text in the Donate Modal

src/pages/DonateModal/DonateModal.tsx, tests/about.spec.ts
links under "Attributions" should lead to the attr origins.
=> test: add test for About/Attributions

tests/visual.spec.ts
Many of our tests got aborted because we used deprecated iPhone 8
https://applitools.com/docs/topics/overview/ufg-devices.html
This pull request renders our applications on iphone 16 instead, and that's fixing the tests
=> test: upgrade visual test iphone

src/layout/header/DonationButton.tsx, src/pages/DonateModal/DonateModal.tsx
Sorry about the last PR 🤦‍♂️, I'm still new in this.
the same things are written both in DonateModal and DonateButton, so we can simply export it instead of writing it twice.
as written in  #934
=> refactor:  use export instead of duplicated code

src/pages/DonateModal/DonateModal.tsx
the same things are written in DonateModal and DonateButton, so we can simply export it instead of writing it twice.
There's another problem where
the modal is using an aqua themed color instead of white, if it's intended I apologize
=> style: change DonationModal color

src/pages/DonateModal/DonateModal.tsx
Dynamically changes DonationModal to support (hopefully) most devices, 
as written in #942
=> fix: allow donate modal to dynamically change for devices 

tests/about.spec.ts, tests/tripExistence.spec.ts
1. added a test for verifying the items inside "trip existance"
2. fixed the Applitools link under "about" (it suddenly broke for me for some reason.
* "Choosing params" test was suddenly stuck for me (line 27, no options to choose under "חברה מפעילה"'
I want to see if it fails in the git checks as well, or it's only happens for me :/
=> test: items under trip existence

src/hooks/useSingleLineData.ts
Fixes #902.
Fixes the following issues:
1. Single lines times stopped at 6PM
2. First lines were from 11PM the day before
3. The wrong time was used to filter the times (recorded at times instead of scheduled start time) - which resulted in issue 2.
Optimizations:
1. Optimized the useMemo to return an empty array if no positions passed the filter (typically when no line is chosen yet)
2. Switched to using a Set to ensure times can only appear in options once
Taken at 22:58 (two minutes before the next bus is scheduled)
Taken at 23:00 (after the bus is scheduled)
=> fix: time related issues in the "map by line" page

tests/publicAppeal.spec.ts, tests/tripExistence.spec.ts
I added a test to ensure the existence of all the "public appeal" headers.
=> test: public appeal page items

src/App.tsx, src/locale/en.json, src/pages/timeBasedMap/index.tsx
Fix translation issues from Hebrew to English
This PR addresses several issues related to the translation from Hebrew to English:
- Corrected the time format to adapt based on the active language:
- In English, the time is displayed as "AM/PM".
- In Hebrew, the time is displayed as "אחר הצהריים" or "בבוקר".
- Used the `i18n.language` property to dynamically switch the locale in Moment.js for proper time formatting in both languages.
- Fixed the `<title>` tag in the document head to correctly update when switching languages.
- Ensured that the title is properly displayed in English when the site is in English.
- Changed a header that was in Hebrew to English to match the selected language.
- Ensured consistency across the page by making sure all headers are translated according to the …
=> chore: add missing translations

src/layout/header/Header.css
Hi, this fix is for the following bug - 
https://github.com/hasadna/open-bus-map-search/issues/974
It seems that in the header.css file the '.main-header' template with the field "justify-content" modified the behavior of the headers icons not to be aligned as expected. I change it to "flex-end" that verify that in each language we are using the headers icons bar will be at the end of line which means the other side as expected. Below there is an example of before and after the change.
Before change:
After change:
=> style: align headers icons

tests/research.spec.ts
After the page loads, type "geek" and get the research page.
=> test: add test for getting to research page with an easter egg

src/pages/components/map-related/MapContent.tsx
Hi, this is my initial PR for the map translation bug - https://github.com/hasadna/open-bus-map-search/issues/950
It currently works only on 'Map by line'. I want to implement that also on 'Time based map' as well.
I think I can improve it mainly with the map URL. I couldn't find better solution at the moment and if we can make the render smoother. I tried to use dependency on the i18n.language but it seems not to work.
Hebrew map:
English map:
=> fix: changing map language

.github/workflows/build.yml
Add a simple fix for the version hash bug - https://github.com/hasadna/open-bus-map-search/issues/917
Please advise how you think this tag should be look on the about page.
=> feat: serve latest commit version

.github/workflows/build.yml
Test and fix the issue with hash.txt file that needs to be created during the build process
=> fix: fix hash.txt issue from build.yaml

.github/workflows/validate.yaml
Seems like chrome for testing doesn't work well on Linux Ubuntu 24.04:
* https://issues.chromium.org/issues/373753919?pli=1
* https://github.com/puppeteer/puppeteer/issues/12818
This PR change `ubuntu latest` to `ubuntu 22`
=> ci: revert linux ubuntu version

src/locale/he.json, src/pages/components/map-related/MapLayers/BusToolTip.tsx
Translate bearing to geographic terms
<paste here>
=> feat: represent bearing as geographic terms

.github/workflows/validate.yaml
fix: add test for checking existannce of public/hash.txt file
=> chore: add hash.txt to the public folder

tests/patterns.spec.ts
As in "Trips history" and "single line map" pages, I also added these tests for "Patterns" page;
a test to verify an API call for gtfs_agencies,
and a test to verify the dateFrom parameter is a recent date.
=> test: add tests for patterns page

tests/missingRides.spec.ts
tests for "Trips that didn't take place" page;
a test to verify an API call for gtfs_agencies,
and a test to verify the dateFrom parameter is a recent date.
=> test: add tests for missing rides

src/hooks/useSingleLineData.ts, src/pages/Map.scss, src/pages/components/FilterPositionsByStartTimeSelector.tsx, src/pages/components/RouteSelector.tsx, src/pages/components/map-related/MapContent.tsx, src/pages/components/map-related/useRecenterOnDataChange.ts, src/pages/singleLineMap/index.tsx, tests/singlelineTest.spec.ts
Display the planned route before selecting a time.
- **SingleLineMapPage**
- Enhanced search functionality.
- Improved event handling.
- **useSingleLineData**
- Use `undefined` values for `startTime` instead of `'0'`.
- Separate the `plannedRouteStops` from `filteredPositions` to allow for independent loading.
- Optimized and refactored code.
- **RouteSelector and FilterPositionsByStartTimeSelector**
- Replace `'0'` with `undefined` values.
- **MapContent**
- Fixed the duplication of keys in `plannedRouteStops`.
- Optimized and refactored code.
-  **useRecenterOnDataChange**
- The map also focuses when `plannedRouteStops` are available.
- Optimized and refactored code.
- **Map.scss**
- Improved readability of `.map-index-title` in dark mode.
- Formatted the file.
- …
=> feat: see planned rout even when no actual ride was executed

src/pages/about/index.tsx, src/pages/components/OperatorSelector.tsx, src/pages/components/RouteSelector.tsx, src/pages/components/StopSelector.tsx, src/pages/dashboard/ArrivalByTimeChart/DayTimeChart.tsx, src/pages/gapsPatterns/GapsPatternsPage.tsx, src/pages/publicAppeal/index.tsx, src/pages/singleLineMap/index.tsx, src/shared/Widget.tsx, src/shared/shared.css, vite.config.ts
- **Widget**: Replace `last-of-type` with `marginBottom` props for consistent UI spacing.  
- **OperatorSelector**, **RouteSelector**: Reintroduce `null` as a possible `value` (was unintentionally removed in an earlier PR).  
- **StopSelector**: Set `getOptionKey`.  
- **Task**: Remove unnecessary `index` props and add `marginBottom` props.
I want to change this before I add the Operator page
=> refactor: widget and selectors

src/api/agencyList.ts, tests/visual.spec.ts
This PR addresses the following changes and fixes:
1. **Client API Update**: Disabled the dynamic date in the `getAgencyList()` method to ensure consistent data retrieval.
2. **Client Test Fix**: Resolved the visual test failure caused by operator discrepancies.
These updates are related to relevant issues: #1128.
=> fix: getAgencyList fallback

.github/workflows/build.yml
this permission change should propagate to the [deploy-preview.yml](https://github.com/hasadna/open-bus-map-search/blob/main/.github/workflows/deploy-preview.yml) workflow 
https://docs.github.com/en/actions/reference/workflows-and-actions/reusable-workflows#access-and-permissions-for-nested-workflows
=> ci: fixing deployment comment
