src/App.tsx
src/api/groupByService.ts
src/api/gtfsService.ts
src/api/siriService.ts
src/api/useVehicleLocations.ts
src/model/pageState.ts
src/model/vehicleLocation.ts
src/pages/RealtimeMapPage.tsx
src/pages/SingleLineMapPage.tsx
src/pages/components/MapLayers/BusLayer.tsx
src/pages/components/timeline/Timeline.tsx
src/pages/components/timeline/TimelineBoard.tsx
src/pages/dashboard/DashboardPage.tsx
src/resources/texts.ts
tsconfig.json

features:
1. develop a new page to investigate a single line at a time
2. make the dashboard nicer
3. adaptions regarding new API features and changes

wip: add SingleLineMapPage

---

package.json
src/api/gapsService.ts

Supporting requests of the form: 
https://open-bus-stride-api.hasadna.org.il/rides_execution/list?limit=100&get_count=false&date_from=2023-07-23&date_to=2023-07-23&operator_ref=25&line_ref=23378

Using new gaps api

---

src/App.tsx
src/pages/RealtimeMapPage.tsx
src/pages/dashboard/DashboardPage.scss
src/pages/dashboard/DashboardPage.tsx

no I can compile and run without Warnings the pages: dashboard, timeline, gaps and single-line-map.
to fix the warning in real time map page, I need redesign the page.

Fix errors and warnings

---

src/App.tsx

It's a little bit hacky but does the trick (except for some edge cases)
buildup toward linking to specific rides

feat: save search params to url

---

src/pages/dashboard/HbarChart/HbarChart.scss
src/pages/dashboard/HbarChart/HbarChart.tsx

style: ellipsis

---

src/pages/components/LineSelector.tsx

**This pull request fixes the debounce bug**
- related to issue #38 
@ShayAdler @NoamGaash

fix: debounce bug

---

tests/example.spec.ts

* fix test - the MUI works differently with dates
* smarted back-end mock

test: mock traffic

---

tests/example.spec.ts

fix: tests

---

src/pages/About.tsx
src/resources/texts.tsx

text enhancements (approved by Dorit)

fix: about page

---

src/App.tsx
tests/dashboard.spec.ts

When <Navigate to={PAGES[0].key} replace /> is placed in a separate component, redirection functions correctly otherwise it doesn't work. Not sure what the exact root cause here but it must be related to component lifecycle and initialisation.
Fix #82

Fix the home page

---

README.md

README.md has a poorly formatted link

fix: design file link

---

Dockerfile

fix: repair CI pipeline

---

.github/CODEOWNERS

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
Feel free to edit this file

ci: create CODEOWNERS

---

src/api/gapsService.ts

just a better type for `parseTime`

refactor: gapsService

---

src/pages/GapsPage.tsx
src/pages/RealtimeMapPage.tsx
src/pages/SingleLineMapPage.tsx
src/pages/TimelinePage.tsx
src/pages/components/DateSelector.tsx
src/pages/components/TimeSelector.tsx
src/pages/components/utils/dateAndTime.tsx

fix: datetime validation

---

src/api/useVehicleLocations.ts
src/pages/RealtimeMapPage.tsx
src/pages/SingleLineMapPage.tsx

new date created every time the hook was called, so the "useEffect" ran unnecessarily

perf: useVehicleLocations usage

---

tests/about.spec.ts

test: about page

---

src/api/gtfsService.ts
src/api/useVehicleLocations.ts
src/pages/SingleLineMapPage.tsx

Please describe the suggested changes
<-- paste here -->

fix: single line map page

---

src/api/groupByService.ts
src/pages/dashboard/DashboardPage.tsx

add a loading animation at places of all three charts at dashboard page
closes #123

feat: add skeleton animation at dashboard

---

src/resources/texts.tsx

text: make less offensive

---

src/pages/GapsPatternsPage.scss
src/pages/GapsPatternsPage.tsx
src/pages/useGapsList.ts

Added a skelton to as a loading indicator to the patterns page while fetching data.
solving #125

Add loading skeleton to the patterns page

---

.github/workflows/lint.yml
.github/workflows/playwright.yml

Add a separate file for lint in github workflow
- Remove lint job in playwright workflow
- Add lint job in a new lint workflow file

Add github lint workflow file

---

README.md

displaying testing command list as a table

docs: better styling for testing instructions

---

src/pages/dashboard/HbarChart/HbarChart.scss
src/pages/dashboard/HbarChart/HbarChart.tsx

changed the hbarChart style #147

updated HbarChart style

---

README.md

Please describe the suggested changes
<-- paste here -->

docs: update link to api repo at readme

---

tests/menu.spec.ts

Added tests to check if the texts in the menu are appearing in order.
- `src/pages/components/header/menu/Menu.tsx`

Added Unit Test for Menu.tsx

---

src/locale/he.json

fix: text in menu (gaps_patterns_page_title)

---

src/pages/dashboard/DashboardPage.tsx

mobile support
current situation:
after my fix:

fix(mobile): make byhour filter like others

---

index.html

animation that appears before the js files loaded (before first rendering)
and stops when js starting to render react components
https://github.com/hasadna/open-bus-map-search/assets/1336862/685cbffb-962a-498e-9b46-98ddb860afdd

feat: add a preloader aniamtion to the site

---

src/App.tsx
src/routes/index.tsx

in order to reduce code of App.tsx file and make its code more readable-
i think, it will better to move routes to its dedicated file 
look and feel should remain the same as before

refactor: move routes logic to routes file

---

.github/pull_request_template.md

What: Make Guidelines as comments, they don't need to show
Why: So we don't need to delete them manually
<paste here>
https://github.com/hasadna/open-bus-map-search/assets/76536506/7b95021e-9d20-4788-b527-f76cafc2e259

[Fix] Pull_Request_Template update

---

src/App.tsx
src/pages/components/header/sidebar/menu/Menu.tsx
src/routes/index.tsx

instead of add all routes in static way - it is better to use loop
closes #185 
no need here

refactor: use loop for routes definition

---

src/pages/About.tsx
tests/about.spec.ts

purpose of this PR - to add more test cases for About page
<paste here>

test(e2e): improve tests for about page

---

.gitignore
package.json

use stable version of yarn.
its important for storybook build command - https://github.com/storybookjs/storybook/issues/24318

chore: upgrade yarn

---

src/api/gapsService.ts
src/api/geoService.ts
src/api/gtfsService.ts
src/api/siriService.ts
src/complaint/complaint.js
src/pages/TimelinePage.tsx
src/pages/components/timeline/Timeline.tsx
src/pages/dashboard/HbarChart/HbarChart.tsx

chore: remove console.log statements 

---

tests/SelectorsModel.ts
tests/clearButton.spec.ts
tests/realtimemap.spec.ts

Playwright clearButton Test and change code structure of this test
@NoamGaash I choose it to be merged to the #226 pr , so hopefully it will make less conflicts . Also I created this branch from the branch in #226 so merging to main will be a problem here, In my opinion.
<paste here>
Don't need here

[Fix] Playwright clearButton Test and change structure

---

README.md
src/pages/EasterEgg/EasterEgg.tsx

- add image in the letter (favicon image)
- change colors like the dashboard colors
- add in readme
<paste here>
https://github.com/hasadna/open-bus-map-search/assets/76536506/e1811e11-21b3-4d5d-9b43-3dc86f640fa1
@NoamGaash What do you think?

feat: modify StoryBook secret easteregg design 

---

src/pages/gapsPatterns/GapsPatternsPage.tsx

fix size of inputs at mobile
closes #238

Fix inputs at mobile, at gaps patterns page

---

src/layout/sidebar/menu/Menu.tsx

replace `defaultSelectedKeys` to `selectedKeys` in `Menu` 
#246

fix issue 246

---

tests/clearButton.spec.ts

fix bug in test file ,it tried to choose unpickable date
<paste here>

fix bug in test file ,it tried to choose unpickable date

---

src/pages/dashboard/AllLineschart/AllLinesChart.tsx
src/pages/dashboard/ArrivalByTimeChart/DayTimeChart.tsx
src/pages/dashboard/DashboardPage.tsx
src/pages/dashboard/WorstLinesChart/WorstLinesChart.tsx

First part of the split issue #258- Moved the logic of AllLineschart to a separate component.
Also, arranged the declarations and imports in the header of the tsx file to be more organized (Let me know if you want me to revert that)
Page should look and act the same.

moved AllLinesChart to separate component

---

.env
src/api/agencyList.ts
src/api/apiConfig.ts

can be better to use .env file 
(in order be able to change api  uri easily if we wish)
no visual changes here

chore: take API uri from .env file

---

src/pages/about/About.scss
src/pages/about/index.tsx
src/routes/index.tsx

add some improvements to about page styling

feat: improve design of about page

---

package.json
src/App.tsx
src/routes/MainRoute.tsx
yarn.lock

upgrade antd to version 5
desktop:
mobile:

chore: upgrade antd package to v5

---

src/locale/en.json
src/locale/he.json
src/locale/utils.ts
src/pages/components/RouteSelector.tsx
src/pages/components/StopSelector.tsx
src/pages/components/timeline/TimelinePoint.tsx
src/pages/dashboard/AllLineschart/AllLinesChart.tsx
src/pages/dashboard/ArrivalByTimeChart/DayTimeChart.tsx
src/pages/dashboard/DashboardPage.tsx
src/pages/dashboard/WorstLinesChart/LineHbarChart/HbarChart/HbarChart.tsx
src/pages/dashboard/WorstLinesChart/WorstLinesChart.tsx
src/pages/gapsPatterns/GapsPatternsPage.tsx
src/pages/realtimeMap/index.tsx
src/pages/singleLineMap/index.tsx

I think part 6 will be the last one:)
I Moved the formatted function from texts file to local>utils.ts. In RouteSelector, StopSelector.
I also removed TEXTS import from: SingleLineMapPage, AllLinesChart, DashboardPage, DayTimeChart, WorstLinesChart, HbarChart, GapsByHour & GapsPatternsPage, RealtimeMapPage

Removing texts part5

---

src/pages/components/timeline/Timeline.tsx
src/pages/components/timeline/TimelinePoint.tsx

chore: text suggestion

---

CONTRIBUTION.md

more explanations for help to beginner contributors
not relevant here

docs: add more sections to contribution guide

---

.github/workflows/validate.yaml

ci: add report comment

---

CONTRIBUTION.md

The link didn't work I've change to a link connecting to the channgel in Ma'akaf communiy.

docs: working Discord link

---

CONTRIBUTION.md
README.md

This pull request adds detailed instructions on how to run the project locally. It includes steps to fork the repository, clone it to your local machine, navigate to the project directory, install dependencies, and run the project. These instructions will help new contributors get started with the project easily.

docs: Add instructions for running the project locally

---

src/pages/dashboard/AllLineschart/AllLinesChart.tsx
src/pages/dashboard/DashboardPage.scss

fix: replace tooltip class by ant icon

---

src/model/operator.ts
src/pages/components/OperatorSelector.tsx
src/pages/dashboard/DashboardPage.tsx

solves multiple calls to getAgenciesList api #346

perf: reduce calls of agencyList api

---

.gitpod.yml

adds support for [gitpod](https://gitpod.io/)

chore: add `.gitpod.yml`

---

src/routes/index.tsx

Updated the about icon in sidebar
fixes: #341 
Before : 
After

feat: updated the about icon in sidebar

---

CONTRIBUTING.md

Instruction of running a project at gitpod.io remote editor
Not relevant

docs: add instruction of using gitpod

---

src/pages/dashboard/DashboardPage.tsx

to restore the missing scrollbars
before
after

style: restore missing scrollbars at dashboard widgets

---

tests/about.spec.ts

titles of the "about" tests should be more clear about: what exactly they are trying to test
not relevant here

test: titles of the "about" tests should be more clear

---

src/pages/gaps/index.tsx
src/pages/historicTimeline/index.tsx

fix: add titles to gaps-page

---

README.md

i renamed CONTRIBUTION to CONTRIBUTING and forgot to update the link
not relevant

docs: change link to contributing.md file

---

README.md

add some useful link to the readme

docs(readme): useful links

---

src/layout/header/Header.tsx
src/layout/header/ToggleThemeButton.tsx

Created a separate component for ToggleTheme button. #376 
First PR 👍 
Please review @amabelleS @NoamGaash 
<paste here>

refactor: extract ToggleTheme button to a component

---

src/pages/BugReportForm .tsx
src/pages/BugReportForm.scss

Updated styles in the BugReportForm.scss and BugReportForm.tsx file to ensure compatibility with the dark theme.
I'm new to Github any feedback is appreciated

fix: dark theme styling issue in BugReportForm.tsx

---

src/pages/historicTimeline/index.tsx

fix: remove duplicate title & description

---

Dockerfile

the storybook thingy stopped working.
this pr will fix it.

fix: storybook

---

index.html
src/layout/ThemeContext.tsx

fix: locale direction

---

src/pages/dashboard/ArrivalByTimeChart/ArrivalByTimeChats.scss

feat: ArriveByTimeChart scroll snapping

---

src/App.tsx
src/pages/dashboard/ArrivalByTimeChart/ArrivalByTimeChart.tsx

- set default settings for moment.js in App.tsx (tz and locale)
- display day + date on by-day
- display day + hour on by-hour
Adding moment.js setup to MainRoute didn't work, thus I left it in App.tsx
#25 
@NoamGaash @ArkadiK94

feat: Format dates to ArriveByTimeChart

---

src/routes/index.tsx
tests/menu.spec.ts

it's not implemented,
let's hide it from the menu until it's ready

chore: hide bug report form

---

src/layout/sidebar/logo.tsx
src/layout/sidebar/sidebar.scss

This change resolves issue #394 make the logo white on dark mode

feat: made logo white on dark mode

---

package-lock.json
package.json
src/model/operator.ts
src/pages/components/OperatorSelector.tsx
src/pages/dashboard/WorstLinesChart/WorstLinesChart.tsx

I added תנופה to one of the relevant operators

chore: Adding tnufa to dropdown in dashboard #423

---

.stylelintrc.json
eslint.config.js
package-lock.json
package.json
src/App.scss
src/index.css
src/layout/header/Header.css
src/layout/sidebar/menu/menu.scss
src/layout/sidebar/sidebar.scss
src/pages/BugReportForm.scss
src/pages/Map.scss
src/pages/components/ClearButton.scss
src/pages/components/DisplayGapsPercentage.scss
src/pages/components/Selector.scss
src/pages/components/utils/customCluster/customCluster.scss
src/pages/dashboard/AllLineschart/OperatorHbarChart/operatorsHbarChart.scss
src/pages/dashboard/ArrivalByTimeChart/ArrivalByTimeChats.scss
src/resources/variables.scss

add a CSS linter - we didn't have any

chore: lint css

---

tests/dashboard.spec.ts

test: make sure dark mode state loads from local storage

---

src/layout/ThemeContext.tsx
src/layout/header/GitHubLink/GitHubLink.scss
src/layout/header/Header.css
src/layout/header/Header.tsx

I changed the bg color in dark mode to be a bit nicer specified in issue #356
If you want a different color just say so
-before
-after

style: changed dark mode background color

---

eslint.config.js

ci: add no-unused-modules rule

---

tests/utils.ts
tests/visual.spec.ts

* make sure the test won't fail on visual things
* there is another commit status that Eyes makes to show us the status of the visual tests (it get's updated automatically when a visual diff is approved)

test: Eyes-GitHub integration

---

src/pages/Profile.tsx

Added a map to the bottom of this page: 
Fix #542

feat(line-profile): add a map

---

CONTRIBUTING.md

I'd like to encourage contributors to get access to the repo instead of forking it
<paste here>

docs: don't fork us

---

nx.json

get rid of nx cloud - it makes our build fail for no reason :angry:

ci: remove nx cloud

---

.github/workflows/complaint.yml
.github/workflows/lint-pr.yml
.github/workflows/preview.yml
.github/workflows/release-please.yml
.github/workflows/validate.yaml

Mainly small changes and a whole re-write to `validate.yaml`

ci: refactor workflows

---

src/routes/index.tsx

fix: refresh client when new version is released

---

README.md

uptate reacme after deleting easter egg and creating butten to change languages
<paste here>
@Tamir198

docs: Remove "Type 'english'" command from README.md

---

.prettierrc
CONTRIBUTING.md
eslint.config.js
src/pages/components/map-related/MapWithLocationsAndPath.tsx

Resolve #726 
- Center the map to the mean of all available data points whenever new data is loaded to the map
- Fix some typos in `CONTRIBUTING.md`
- Add `.prettierrc` file for a smooth prettier development experience

style: center map automatically when data changes

---

.github/workflows/validate.yaml

based on https://github.com/peaceiris/actions-gh-pages/issues/153 (@peaceiris solutions)

ci: don't try publishing test results on fork

---

.github/workflows/validate.yaml

make the CI more verbose
reason - https://github.com/hasadna/open-bus-map-search/pull/744#issuecomment-2105941856

ci: tell what failed

---

src/api/useVehicleLocations.ts
src/hooks/useSingleLineData.ts

Fix performance problem we had in single line page

perf(SingleLinePage): don't fetch irrelevant data

---

src/routes/index.tsx

fix: remove duplicated header donation button

---

.github/workflows/coverage.yml

ci: add commit sha fallback

---

tests/mainHeader.spec.ts

add a test with Playwright that make sure there is no duplicate SVG

test: header-links icons should be unique

---

src/pages/homepage/HomePage.scss
src/pages/homepage/HomePage.tsx

After hiding the description on the pages themselves. I added them to the home page by the links.

refactor: improve homepage layout and add descriptions to page links

---

src/pages/gapsPatterns/GapsPatternsPage.scss
src/pages/gapsPatterns/GapsPatternsPage.tsx

refactor: dark mode alert

---

src/layout/header/Header.tsx

show a warning regarding some missing data we lately have

chore: add missing data notification

---

src/pages/DataResearch/DataResearch.tsx
src/pages/components/DateSelector.tsx
src/pages/components/TimeSelector.tsx
src/pages/components/utils/dateAndTime.tsx
src/pages/lineProfile/LineProfile.tsx
src/pages/singleLineMap/index.tsx

following https://github.com/hasadna/open-bus-map-search/pull/823#issuecomment-2182401886

refactor(DateSelector): better types and i18n

---

tests/timeline.spec.ts

this company replaced by "דרך אגד"

test: remove deprecated operator (אגד תעבורה)

---

src/pages/components/map-related/MapLayers/ComplaintModal.tsx

Refactor the code of modal complaint to use material UI components that auto-support dark/light mode & auto-scroll.
Also the components fix minor ui bugs.
I didn't change the functionality itself.
I didn't fix the translations

refactor: apply code review comments for modal complaint

---

.github/dependabot.yml

ci: remove aviv from dependabot reviewers

---

.github/workflows/deploy-preview.yml
.github/workflows/validate.yaml

ci: published tests results commit status

---

.github/workflows/build.yml
.github/workflows/complaint.yml
.github/workflows/deploy-preview.yml
.github/workflows/validate.yaml

ci: update actions/upload-artifact to v4

---

src/layout/header/Header.tsx

chore: remove warning message

---

.github/workflows/coverage.yml
.github/workflows/validate.yaml
package-lock.json
package.json

some of out visual tests gets aborted.
this pr [adds some log artifacts](https://help.applitools.com/hc/en-us/articles/360006914932-How-can-I-enable-Applitools-Eyes-SDK-traces-logs) so Applitools support can help

ci: add applitools  logs

---

tests/bugReport.spec.ts

A test to validate that the instruction video inside the bug report section exists and that it is playable.

test: add test for istruction video for bug report

---

src/pages/dashboard/ArrivalByTimeChart/ArrivalByTimeChart.tsx
tests/dashboard.spec.ts

The "Arrival by day" chart in the dashboard was broken,
This PR fixes it

fix: arrival by day chart

---

tests/singlelineTest.spec.ts

A test to check the tooltip that appears after clicking a map point in 'single line map'.

test: add test for single line tooltip

---

.github/workflows/cd.yml

Added insertion of hash.txt file with commit hash also for deployment process and include it in the production image.

fix: add hash.txt to cd.yaml (deployment) file

---

tests/tripExistence.spec.ts

Tests for API requests for agencies and date_from under trip existence.
I hope this is fine, as my API knowledge is still limited, I used the help of Claude ;)

test: add tests for gtfs agencies

---

package.json
src/layout/ThemeContext.tsx
src/pages/components/DateSelector.tsx
src/routes/MainRoute.tsx

- ~~Displays Hebrew month name in English locale~~
- ~~Arrow buttons direction on the wrong side~~

fix: Calendar displays hebrew month name in english locale

---

src/layout/index.tsx
src/layout/sidebar/SideBar.tsx
src/pages/homepage/HomePage.scss
src/pages/homepage/HomePage.tsx

Fix Scrolling Problem on HomePage and Layout
**HomePage.tsx**
- Refactor the useEffect resize event.
**HomePage.scss**
- Formatted file.
- Fixed the footer styling by adjusting its position, width, and margin.
**SideBar.tsx**
- Fixed error in the Drawer.
- Added `overflow: auto;` to add scroll to the sidebar.
**layout/index.tsx**
- Ensured that the scroll was hidden.

fix: Bug Horizontal scroll

---

tests/clearButton.spec.ts
tests/dashboard.spec.ts
tests/operator.spec.ts
tests/timeline.spec.ts
tests/utils.ts
tests/visual.spec.ts

- Operator Input states
- Operator Info Card
- Operator Gaps Card
- Operator Routes Card
- Operator Visual Test

test: Add Tests for Operator Page

---

src/locale/en.json
src/locale/he.json
src/pages/singleLineMap/index.tsx

i dont know how i forget to add this 😵‍💫

refactor: added translate to toggle button in singleline map

---

applitools.config.cjs

some tests are failing because the timeout is too short, I'd like to fix that

test: increase sb render timeout

---

.github/workflows/validate.yaml

ci: fix test results commit status
